### ISSUE TITLE
How to install ngvas?

### ISSUE THREAD

**Issue by wCarrie** [patrimart/ngvas#11]
i need use ngvas in angular4,i want to know how to import ngvas ,i used "npm install ngvas ,but it is a wrong order,i can not run my issue,help.

**Comment by patrimart** [comment]
It sounds like `npm install ngvas` isn't working for you. That is the correct command. I will need more information to try to help. Can you paste the error message you are seeing?

**Comment by wCarrie** [comment]
today i update my  project ,and it works.it is ok ,thank you so much

**Comment by patrimart** [comment]
Awesome. Good luck!

**Comment by wCarrie** [comment]
What is the best way to set background-image on the canvas?

**Comment by patrimart** [comment]
You can set the background color via CSS.
```
canvas { background: red; }
```
`ngvas.getShape().context` may work, if you can get a ref to the `<ngvas>` component.

**Comment by wCarrie** [comment]
i do not know how to get 'ngvas.getShape().context', it meas i can not get this ele

**Comment by wCarrie** [comment]
in your demo,i can not find any css or ts,just html ,so i maybe difficult for me to draw a complicated page of using ngvas.
