### ISSUE TITLE
ERROR in NgvasModule is not an NgModule

### ISSUE THREAD

**Issue by magar91** [patrimart/ngvas#3]
Hello, I tried to use ngvas on a project created through the angular-cli, I installed ngvas with npm with `npm install ngvas` I added the NgvasModule to the app.module.ts file, but when I try to run the project with ng serve this error shows up:

```terminal
ERROR in NgvasModule is not an NgModule
```

**Comment by patrick-martin-shoutpoint** [comment]
That just requires a release compiled with `ngc`. I'll attempt to resolve this within the day.

**Comment by patrimart** [comment]
v0.7.4 package should play well with angular-cli now.
