### ISSUE TITLE
canvas max size?

### ISSUE THREAD

**Issue by rui-cruz** [patrimart/ngvas#8]
Hi,

I was trying a fast prototype with ngvas, but seems its limited to 800x600?
I have: <ngvas [width]="frame.width" [height]="frame.height">

On inspector I see: <canvas _ngcontent-c9="" width="800" height="600"></canvas>

my frame have width=1500 and height=1000

Hope its a quick fix!
Thank you

**Comment by patrimart** [comment]
I tried setting the dimensions to 900x900 in the example application on Plunkr with no issue.

https://plnkr.co/edit/Kc57baYFUnSY8MfDznZs?p=preview

There's nothing in the code or any reason I can imagine for imposing that limit. I wonder if possibly some "container" element in your application is cropping the canvas.

**Comment by rui-cruz** [comment]
I will try to figure it out.. I'm using material2 theme and some directives, maybe something is messing with it..
